### ISSUE TITLE
Adding Params to engine construct

### ISSUE THREAD

**Issue by jojoduquartier** [jojoduquartier/dsdbmanager#31]
There are some arguments like `charset` etc. that are best when used in the `create_engine(...)` part directly. So perhaps the easiest way to accommodate those would be to add another argument that is a dict and takes those specific things. Order of insertion might matter but with python 3.6+ that should be ok. Investigate further!

Why charset? sqlalchemy default encoding can cause the data to miss some accents and stuff like that. i.e. N tilde requires a different encoding.

**Comment by CATHounyo** [comment]
`connect_args` seems to work so `connect_args = {'encoding': 'utf8'}` for example. Just pass that argument downstream from user.

**Comment by jojoduquartier** [comment]
For sqlalchemy engine arguments, the user should proceed with direct connection i.e. for example:
```
from dsdbmanager import from_engine
from dsdbmanager.oracle_ import Oracle
db = Oracle('some_database_name')

# it's possible to use the ConfigFilesManager object in dsdbmanager.configuring
# to get the username and password and just unpack it in the line below
engine = db.create_engine(username, password, connect_args = {'encoding': 'utf8'})

dbobject = from_engine(engine)

```

The dboject is mainly to view metadata and available tables/views :)
